/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatsDialog.java
 *
 * Created on 2012-01-10, 11:30:32
 */
package poker;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siesiek
 */
public class StatsDialog extends javax.swing.JDialog {

    /** Creates new form StatsDialog */
    public StatsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            System.out.println(PokerApp.getApplication().loggedUser.getId());
            GameStats[] games = GameStats.getAllGames(PokerApp.getApplication().loggedUser.getId());
            if(games.length > 0){
                gamesLabel.setText(""+games.length);
                roundsLabel.setText(""+GameStats.getAllRounds(PokerApp.getApplication().loggedUser.getId()));
                victoryLabel.setText(""+GameStats.getAllVictory(PokerApp.getApplication().loggedUser.getId()));
                maxRoundsLabel.setText(""+GameStats.getMaxRounds(PokerApp.getApplication().loggedUser.getId()));
                maxVictoryLabel.setText(""+GameStats.getMaxVictory(PokerApp.getApplication().loggedUser.getId()));
                avgRoundsLabel.setText(""+GameStats.getAvgRounds(PokerApp.getApplication().loggedUser.getId()));
                avgVictoryLabel.setText(""+GameStats.getAvgVictory(PokerApp.getApplication().loggedUser.getId()));
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                for(GameStats game : games){
                    model.addRow(game.toArray());
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(StatsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        victoryLabel = new javax.swing.JLabel();
        roundsLabel = new javax.swing.JLabel();
        gamesLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maxVictoryLabel = new javax.swing.JLabel();
        maxRoundsLabel = new javax.swing.JLabel();
        avgRoundsLabel = new javax.swing.JLabel();
        avgVictoryLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Twoje statystyki");

        jLabel1.setText("Liczba rozegranych gier:");

        jLabel2.setText("Liczba wszystkich rozdań:");

        jLabel3.setText("Liczba wszystkich zwycięstw:");

        victoryLabel.setText("0");

        roundsLabel.setText("0");

        gamesLabel.setText("0");

        jLabel4.setText("Maksymalna liczba rozdań:");

        jLabel5.setText("Maksymalna liczba zwycięstw:");

        jLabel6.setText("Średnia liczba rozdań:");

        jLabel7.setText("Średnia liczba zwycięstw:");

        maxVictoryLabel.setText("0");

        maxRoundsLabel.setText("0");

        avgRoundsLabel.setText("0");

        avgVictoryLabel.setText("0");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jLabel8.setText("Twoje gry");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data rozegrania", "Liczba rozdań", "Liczba zwycięstw"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gamesLabel)
                                    .addComponent(roundsLabel)
                                    .addComponent(victoryLabel)))
                            .addComponent(jLabel8))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avgVictoryLabel)
                            .addComponent(avgRoundsLabel)
                            .addComponent(maxRoundsLabel)
                            .addComponent(maxVictoryLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(gamesLabel)
                    .addComponent(jLabel4)
                    .addComponent(maxRoundsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roundsLabel)
                    .addComponent(jLabel5)
                    .addComponent(maxVictoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(victoryLabel)
                    .addComponent(jLabel6)
                    .addComponent(avgRoundsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(avgVictoryLabel)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                StatsDialog dialog = new StatsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgRoundsLabel;
    private javax.swing.JLabel avgVictoryLabel;
    private javax.swing.JLabel gamesLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel maxRoundsLabel;
    private javax.swing.JLabel maxVictoryLabel;
    private javax.swing.JLabel roundsLabel;
    private javax.swing.JLabel victoryLabel;
    // End of variables declaration//GEN-END:variables
}
